// Funillion catalog: cities, areas, categories and event templates.
// Everything here is static reference data used by the seed + aggregation pipeline.

const CITIES = [
  { id: 'delhi', name: 'Delhi NCR', short: 'Delhi', state: 'Delhi', lat: 28.6139, lng: 77.2090, weight: 1.4, speed: 18,
    areas: [
      ['Hauz Khas', 28.5494, 77.2001, 'south'], ['Connaught Place', 28.6315, 77.2167, 'central'], ['Mehrauli', 28.5244, 77.1855, 'south'],
      ['Saket', 28.5245, 77.2066, 'south'], ['Chandni Chowk', 28.6506, 77.2303, 'north'], ['Dwarka', 28.5921, 77.0460, 'west'],
      ['Shahpur Jat', 28.5494, 77.2150, 'south'], ['Cyber Hub, Gurugram', 28.4951, 77.0888, 'ncr'], ['Sector 18, Noida', 28.5708, 77.3261, 'ncr'],
      ['Lajpat Nagar', 28.5677, 77.2433, 'south'], ['Rajouri Garden', 28.6415, 77.1209, 'west'], ['Vasant Kunj', 28.5293, 77.1532, 'south'],
      ['North Campus', 28.6880, 77.2090, 'north'], ['Aerocity', 28.5504, 77.1210, 'west'] ] },
  { id: 'mumbai', name: 'Mumbai', short: 'Mumbai', state: 'Maharashtra', lat: 19.0760, lng: 72.8777, weight: 1.35, speed: 16,
    areas: [
      ['Bandra West', 19.0596, 72.8295, 'west'], ['Andheri West', 19.1364, 72.8296, 'west'], ['Lower Parel', 18.9953, 72.8302, 'central'],
      ['Colaba', 18.9067, 72.8147, 'south'], ['Juhu', 19.0988, 72.8267, 'west'], ['Powai', 19.1176, 72.9060, 'central'],
      ['BKC', 19.0660, 72.8656, 'central'], ['Kala Ghoda', 18.9281, 72.8317, 'south'], ['Versova', 19.1318, 72.8150, 'west'] ] },
  { id: 'bengaluru', name: 'Bengaluru', short: 'Bengaluru', state: 'Karnataka', lat: 12.9716, lng: 77.5946, weight: 1.35, speed: 15,
    areas: [
      ['Koramangala', 12.9352, 77.6245, 'south'], ['Indiranagar', 12.9719, 77.6412, 'east'], ['MG Road', 12.9756, 77.6068, 'central'],
      ['HSR Layout', 12.9121, 77.6446, 'south'], ['Whitefield', 12.9698, 77.7500, 'east'], ['JP Nagar', 12.9063, 77.5857, 'south'],
      ['Church Street', 12.9755, 77.6040, 'central'], ['Malleshwaram', 13.0035, 77.5700, 'north'] ] },
  { id: 'hyderabad', name: 'Hyderabad', short: 'Hyderabad', state: 'Telangana', lat: 17.3850, lng: 78.4867, weight: 1.15, speed: 20,
    areas: [
      ['Jubilee Hills', 17.4326, 78.4071, 'west'], ['Banjara Hills', 17.4156, 78.4347, 'central'], ['HITEC City', 17.4435, 78.3772, 'west'],
      ['Gachibowli', 17.4401, 78.3489, 'west'], ['Secunderabad', 17.4399, 78.4983, 'north'], ['Kondapur', 17.4700, 78.3570, 'west'] ] },
  { id: 'chennai', name: 'Chennai', short: 'Chennai', state: 'Tamil Nadu', lat: 13.0827, lng: 80.2707, weight: 1.0, speed: 19,
    areas: [
      ['T Nagar', 13.0418, 80.2341, 'central'], ['Besant Nagar', 13.0002, 80.2668, 'south'], ['Nungambakkam', 13.0569, 80.2425, 'central'],
      ['Mylapore', 13.0368, 80.2676, 'central'], ['OMR', 12.9010, 80.2279, 'south'], ['Anna Nagar', 13.0850, 80.2101, 'north'] ] },
  { id: 'kolkata', name: 'Kolkata', short: 'Kolkata', state: 'West Bengal', lat: 22.5726, lng: 88.3639, weight: 1.0, speed: 17,
    areas: [
      ['Park Street', 22.5539, 88.3522, 'central'], ['Salt Lake', 22.5867, 88.4171, 'east'], ['Ballygunge', 22.5270, 88.3650, 'south'],
      ['New Town', 22.5760, 88.4796, 'east'], ['Esplanade', 22.5646, 88.3510, 'central'], ['College Street', 22.5760, 88.3630, 'north'] ] },
  { id: 'pune', name: 'Pune', short: 'Pune', state: 'Maharashtra', lat: 18.5204, lng: 73.8567, weight: 1.05, speed: 19,
    areas: [
      ['Koregaon Park', 18.5362, 73.8940, 'east'], ['Baner', 18.5590, 73.7868, 'west'], ['Viman Nagar', 18.5679, 73.9143, 'east'],
      ['FC Road', 18.5236, 73.8418, 'central'], ['Kalyani Nagar', 18.5463, 73.9033, 'east'], ['Hinjewadi', 18.5913, 73.7389, 'west'] ] },
  { id: 'ahmedabad', name: 'Ahmedabad', short: 'Ahmedabad', state: 'Gujarat', lat: 23.0225, lng: 72.5714, weight: 0.8, speed: 22,
    areas: [
      ['SG Highway', 23.0300, 72.5070, 'west'], ['Navrangpura', 23.0365, 72.5611, 'central'], ['Law Garden', 23.0258, 72.5590, 'central'],
      ['Prahlad Nagar', 23.0120, 72.5108, 'west'], ['Sabarmati Riverfront', 23.0395, 72.5770, 'central'] ] },
  { id: 'jaipur', name: 'Jaipur', short: 'Jaipur', state: 'Rajasthan', lat: 26.9124, lng: 75.7873, weight: 0.75, speed: 22,
    areas: [
      ['C-Scheme', 26.9080, 75.8000, 'central'], ['MI Road', 26.9170, 75.8110, 'central'], ['Malviya Nagar', 26.8530, 75.8050, 'south'],
      ['Amer', 26.9855, 75.8513, 'north'], ['Vaishali Nagar', 26.9110, 75.7430, 'west'] ] },
  { id: 'chandigarh', name: 'Chandigarh', short: 'Chandigarh', state: 'Chandigarh', lat: 30.7333, lng: 76.7794, weight: 0.65, speed: 24,
    areas: [
      ['Sector 17', 30.7398, 76.7827, 'central'], ['Sector 35', 30.7240, 76.7560, 'central'], ['Industrial Area', 30.7056, 76.8013, 'south'],
      ['Sukhna Lake', 30.7421, 76.8188, 'north'] ] },
  { id: 'lucknow', name: 'Lucknow', short: 'Lucknow', state: 'Uttar Pradesh', lat: 26.8467, lng: 80.9462, weight: 0.65, speed: 21,
    areas: [
      ['Hazratganj', 26.8500, 80.9460, 'central'], ['Gomti Nagar', 26.8560, 81.0050, 'east'], ['Aminabad', 26.8430, 80.9270, 'central'],
      ['Aliganj', 26.8900, 80.9420, 'north'] ] },
  { id: 'goa', name: 'Goa', short: 'Goa', state: 'Goa', lat: 15.4909, lng: 73.8278, weight: 0.85, speed: 26,
    areas: [
      ['Anjuna', 15.5733, 73.7407, 'north'], ['Panjim', 15.4909, 73.8278, 'central'], ['Calangute', 15.5439, 73.7553, 'north'],
      ['Vagator', 15.6030, 73.7336, 'north'], ['Assagao', 15.5950, 73.7690, 'north'], ['Palolem', 15.0100, 74.0232, 'south'] ] },
  { id: 'kochi', name: 'Kochi', short: 'Kochi', state: 'Kerala', lat: 9.9312, lng: 76.2673, weight: 0.6, speed: 20,
    areas: [
      ['Fort Kochi', 9.9658, 76.2421, 'west'], ['MG Road', 9.9716, 76.2856, 'central'], ['Kakkanad', 10.0159, 76.3419, 'east'],
      ['Edappally', 10.0261, 76.3080, 'north'] ] },
  { id: 'indore', name: 'Indore', short: 'Indore', state: 'Madhya Pradesh', lat: 22.7196, lng: 75.8577, weight: 0.6, speed: 22,
    areas: [
      ['Vijay Nagar', 22.7533, 75.8937, 'north'], ['Palasia', 22.7244, 75.8839, 'central'], ['Rajwada', 22.7185, 75.8553, 'central'],
      ['Sarafa Bazaar', 22.7190, 75.8560, 'central'] ] },
].map(c => ({ ...c, areas: c.areas.map(([name, lat, lng, zone]) => ({ name, lat, lng, zone })) }));

// color = poster background, ink = poster text colour
const CATEGORIES = [
  { id: 'music', label: 'Live Music', icon: '♬', color: '#d3dbf3', ink: '#202644' },
  { id: 'comedy', label: 'Comedy', icon: '☺', color: '#ffd84d', ink: '#3a2a00' },
  { id: 'hackathons', label: 'Hackathons', icon: '⌘', color: '#1f2a1f', ink: '#e4ff54' },
  { id: 'bhajan', label: 'Bhajan Clubbing', icon: '✺', color: '#ff9a3d', ink: '#4a1700' },
  { id: 'parties', label: 'Parties', icon: '✦', color: '#2b1740', ink: '#ff8ad8' },
  { id: 'meetups', label: 'Meetups', icon: '◎', color: '#c9f0dc', ink: '#0f4a2e' },
  { id: 'workshops', label: 'Workshops', icon: '✎', color: '#d9b6e7', ink: '#492552' },
  { id: 'openmic', label: 'Open Mic & Poetry', icon: '✑', color: '#f4e3cf', ink: '#5b2f14' },
  { id: 'theatre', label: 'Theatre', icon: '◐', color: '#7a1f2b', ink: '#ffe3c2' },
  { id: 'food', label: 'Food & Drink', icon: '◉', color: '#ffad65', ink: '#542609' },
  { id: 'arts', label: 'Art & Culture', icon: '◈', color: '#b8e3f2', ink: '#0f3a4a' },
  { id: 'sports', label: 'Sports & Fitness', icon: '⚑', color: '#e4ff54', ink: '#181a17' },
  { id: 'festivals', label: 'Fests & Melas', icon: '❋', color: '#ff6b5b', ink: '#3b0a05' },
  { id: 'networking', label: 'Startups & Networking', icon: '↗', color: '#e8ebdf', ink: '#181a17' },
  { id: 'gaming', label: 'Gaming & Esports', icon: '▶', color: '#101c3a', ink: '#6af0ff' },
  { id: 'wellness', label: 'Wellness & Spiritual', icon: '☯', color: '#dff2d8', ink: '#2f4a22' },
  { id: 'screenings', label: 'Screenings', icon: '▣', color: '#222', ink: '#ffd84d' },
];

// Event templates. {area} / {city} are substituted. hours = possible start hours (24h).
// dur = duration in hours. tiers = [name, price, capacity]. w = frequency weight. wk = weekend bias (1..3)
const TEMPLATES = {
  music: { w: 1.3, wk: 2, hours: [18, 19, 20, 21], dur: 3, image: 'concert.jpg', tags: ['live', 'nightlife', 'indie'],
    titles: ['Sunday Sound Club', 'Indie Nights: {area} Sessions', 'Unplugged Under the Stars', 'Sufi Evenings Live', 'Bollywood Retro Live Band', 'Jazz on the Terrace', 'Hip-Hop Cypher Live', 'Rock Revival Night', 'Carnatic Fusion Evening', 'Lo-fi & Chill Live Set', 'Ghazal Night at {area}', 'The Big Bass Concert'],
    venues: ['The Listening Room', 'Soundbox', 'Echo Terrace', 'The Amp House', 'Riff Café', 'Blue Note Loft', 'The Stage Door'],
    desc: 'Live performances from independent artists and local bands. Good sound, a crowd that actually listens, and a bar that stays open late.',
    tiers: [['General', 499, 180], ['Fan Pit', 999, 60], ['VIP Table (4 pax)', 3999, 8]], labels: ['LIVE · INDIE', 'CONCERT', 'LIVE BAND', 'UNPLUGGED'] },
  comedy: { w: 1.3, wk: 1.6, hours: [19, 20, 21], dur: 1.5, tags: ['standup', 'laughs', 'date'],
    titles: ['Laugh Riot: Stand-up Night', 'Crowd Work Comedy', 'The Punchline Club', 'Hindi Stand-up Special', 'Late Night Roast Show', 'New Material Night', 'Comedy Open Mic Finals', 'Improv Jam: Anything Goes', 'Desi Dad Jokes Live', 'Sketchy Business: Sketch Comedy'],
    venues: ['The Punchline Room', 'Laugh Lounge', 'Chuckle Cellar', 'The Comedy Den', 'Canvas Laugh Store', 'Hasi Ghar'],
    desc: 'A tight lineup of stand-up comics testing sets, trading punchlines and roasting the front row (sit at your own risk).',
    tiers: [['Standard', 399, 120], ['Front Row', 799, 20]], labels: ['STAND-UP', 'COMEDY NIGHT', 'IMPROV'] },
  hackathons: { w: 0.9, wk: 2.4, hours: [9, 10], dur: 24, image: 'hack.jpg', tags: ['tech', 'coding', 'students', 'ai'],
    titles: ['Build/{city}: 24h Hackathon', 'AI Agents Hackathon', 'HackTheCity {city}', 'Climate Tech Buildathon', 'FinTech Hack Sprint', 'Open Source Weekend Hack', 'GenAI Product Jam', 'Web3 & Beyond Hackathon', 'HealthTech Hack Night', 'Student Code Sprint'],
    venues: ['Innovation Hub', 'The Build Garage', 'TechPark Commons', 'Startup Foundry', 'Code Campus Hall'],
    desc: 'A build sprint for developers, designers and product thinkers. Bring a team of 2–4 or find teammates on the spot. Mentors, meals and prizes included.',
    tiers: [['Team Registration (per person)', 0, 300], ['Pro Pass (swag + workshops)', 299, 60]], labels: ['BUILD · COLLABORATE', 'HACKATHON', '24H SPRINT'] },
  bhajan: { w: 0.9, wk: 2, hours: [18, 19, 20], dur: 2.5, tags: ['spiritual', 'music', 'devotional', 'nightlife'],
    titles: ['Bhajan Clubbing Night', 'Kirtan & Chill', 'Satsang Beats', 'Bhakti Bass: Bhajan Club', 'Hare Krishna Jam Session', 'Sufi & Bhajan Clubbing', 'Ram Dhun Remix Night', 'Midnight Kirtan Rave'],
    venues: ['Anand Courtyard', 'The Bhakti Loft', 'Sangam Hall', 'Mandap Terrace', 'Shanti Studio'],
    desc: 'Devotional music meets club energy. Live bhajans and kirtan with a DJ, dhol and a crowd that sings along — alcohol-free, all heart.',
    tiers: [['Entry', 299, 250], ['Front Circle', 599, 40]], labels: ['BHAJAN CLUBBING', 'KIRTAN · LIVE', 'DEVOTIONAL DJ'] },
  parties: { w: 1.3, wk: 3, hours: [21, 22], dur: 4, image: 'concert.jpg', tags: ['nightlife', 'dj', 'dance'],
    titles: ['After Hours: Rooftop Sessions', 'Techno Tuesday', 'Bollywood Night Out', 'Neon Glow Party', 'Afro House Sundowner', 'Retro 90s Throwback', 'Silent Disco', 'Ladies Night Deluxe', 'Deep House Sundays', 'Warehouse Rave'],
    venues: ['Skyline Rooftop', 'The Vault', 'Pulse Club', 'Moonshine Terrace', 'Club Aurora', 'Loft 21'],
    desc: 'DJ sets, dance floor and city lights. Dress code: smart casual. Entry for 21+ with valid ID.',
    tiers: [['Stag Entry', 999, 150], ['Couple Entry', 1499, 100], ['Table (6 pax)', 7999, 10]], labels: ['DJ SET · ROOFTOP', 'CLUB NIGHT', 'PARTY'] },
  meetups: { w: 1.1, wk: 1.8, hours: [10, 11, 16, 17, 18], dur: 2.5, tags: ['community', 'people', 'free'],
    titles: ['Book Club: Monthly Meet', 'Product Folks Meetup', 'Board Games & Coffee', 'Photography Walk', 'Language Exchange Evening', 'Founders Coffee Morning', 'Python Devs Meetup', 'Solo Travellers Meet', 'AI/ML Reading Group', 'Runners Brunch Club', 'Women in Tech Meetup', 'Anime Fans Meetup'],
    venues: ['Third Wave Commons', 'The Community Table', 'Social Hub', 'Café Circle', 'The Reading Room'],
    desc: 'A relaxed community meetup to meet people who like the same things you do. Show up, say hi, stay for the conversation.',
    tiers: [['RSVP', 0, 60], ['RSVP + Coffee', 199, 30]], labels: ['COMMUNITY', 'MEETUP', 'MEET PEOPLE'] },
  workshops: { w: 1, wk: 2, hours: [11, 14, 15, 16], dur: 3, tags: ['learn', 'hands-on', 'creative'],
    titles: ['Pottery for Beginners', 'Make a Little Mess: Art Workshop', 'Candle Making Class', 'Latte Art Masterclass', 'Intro to Figma Workshop', 'Film Photography 101', 'Block Printing Workshop', 'Watercolour Weekend', 'Build Your First AI App', 'Resin Art Session'],
    venues: ['Clay Studio', 'The Maker Space', 'Art Loft', 'Workshop Co.', 'Craft Collective'],
    desc: 'A hands-on beginner-friendly session. All materials included — just bring curiosity. You take home what you make.',
    tiers: [['Participant', 1199, 20], ['Duo (2 seats)', 2199, 8]], labels: ['WORKSHOP', 'HANDS-ON', 'LEARN'] },
  openmic: { w: 1, wk: 1.4, hours: [17, 18, 19], dur: 2.5, tags: ['poetry', 'performance', 'chill'],
    titles: ['Open Mic Night', 'Poetry & Chai', 'Shayari Shaam', 'Storytelling Circle', 'Spoken Word Sundays', 'Songwriters Open Mic', 'Kavi Sammelan Lite'],
    venues: ['The Chai Spot', 'Kahwa House', 'Verse Café', 'Nook & Books', 'Café Qissa'],
    desc: 'Performers get 5 minutes each — poetry, music, stories, comedy. Sign up to perform or just come to listen.',
    tiers: [['Audience', 149, 70], ['Performer Slot', 199, 20]], labels: ['OPEN MIC', 'POETRY', 'SPOKEN WORD'] },
  theatre: { w: 0.8, wk: 2, hours: [16, 19, 20], dur: 2, image: 'wedding.jpg', tags: ['culture', 'drama', 'date'],
    titles: ['Ek Tha Raja: A Hindi Play', 'The Last Train Home', 'Tughlaq Retold', 'Shakespeare in the Courtyard', 'Mimes of the City', 'Blackout: An Immersive Play', 'Balcony Scenes'],
    venues: ['Rangmanch Auditorium', 'The Little Theatre', 'Black Box Studio', 'Open Air Amphitheatre'],
    desc: 'A theatre production by a local repertory. Doors open 20 minutes before showtime; latecomers seated at interval.',
    tiers: [['Balcony', 350, 120], ['Stalls', 650, 150], ['Premium', 1100, 40]], labels: ['THEATRE', 'PLAY', 'STAGE'] },
  food: { w: 1, wk: 2.2, hours: [9, 12, 13, 19], dur: 2.5, tags: ['food', 'walk', 'date'],
    titles: ['A Bite of {area}', 'Street Food Walk', 'Craft Beer Tasting', 'Biryani Trail', 'Chef\'s Table Pop-up', 'Farmers Market Morning', 'Coffee Cupping Session', 'Midnight Food Crawl', 'Regional Thali Festival'],
    venues: ['Old Market Gate', 'The Brew Lab', 'Chef\'s Pantry', 'Pop-up Kitchen', 'The Tasting Room'],
    desc: 'Eat your way through the neighbourhood with a host who knows every stall and story. Come hungry.',
    tiers: [['Tasting Pass', 699, 30], ['Tasting + Drinks', 1199, 15]], labels: ['FOOD WALK', 'TASTING', 'POP-UP'] },
  arts: { w: 0.9, wk: 1.8, hours: [11, 12, 16, 17], dur: 3, tags: ['culture', 'art', 'chill'],
    titles: ['Heritage Walk: {area}', 'Contemporary Art Opening', 'Photography Exhibition', 'Kathak Evening', 'Museum After Dark', 'Street Art Tour', 'Indie Zine Fair', 'Classical Dance Recital'],
    venues: ['City Art Gallery', 'Heritage Gate', 'Kala Kendra', 'The White Wall', 'Cultural Centre'],
    desc: 'Art, heritage and culture curated for curious people. Guided sessions, artists around, conversation encouraged.',
    tiers: [['Entry', 0, 200], ['Guided Tour', 399, 30]], labels: ['ART · CULTURE', 'EXHIBITION', 'HERITAGE'] },
  sports: { w: 1, wk: 2.4, hours: [6, 7, 17, 18], dur: 2, tags: ['fitness', 'outdoor', 'active'],
    titles: ['Sunrise 5K Run', 'Turf Football Pickup', 'Cricket Screening + Box Cricket', 'Rock Climbing Intro', 'Cycling Club Ride', 'Pickleball Social', 'Yoga in the Park', 'Badminton Doubles Mixer', 'Trek & Brunch'],
    venues: ['City Sports Arena', 'The Turf', 'Lakeside Track', 'Boulder Box', 'Central Park Grounds'],
    desc: 'Get moving with a friendly crowd. All levels welcome — equipment available on request.',
    tiers: [['Player', 299, 40], ['Player + Kit', 699, 20]], labels: ['FITNESS', 'SPORTS', 'OUTDOOR'] },
  festivals: { w: 0.8, wk: 2.6, hours: [11, 12, 16], dur: 7, image: 'wedding.jpg', tags: ['festival', 'shopping', 'family', 'music'],
    titles: ['{city} Flea Market', 'Navratri Garba Night', 'College Fest: Rang', 'Durga Puja Pandal Hop', 'Diwali Mela', 'Indie Brands Weekend Bazaar', 'Craft Beer & Music Fest', 'Kite & Food Festival'],
    venues: ['Exhibition Grounds', 'Central Lawns', 'Festival Park', 'Mela Maidan', 'Campus Grounds'],
    desc: 'A full-day festival with stalls, food, live performances and way too many photo spots. Family-friendly.',
    tiers: [['Day Pass', 299, 800], ['Fast Lane Pass', 699, 100]], labels: ['FESTIVAL', 'MELA', 'FEST'] },
  networking: { w: 0.9, wk: 1, hours: [9, 10, 18, 19], dur: 3, tags: ['tech', 'startups', 'career'],
    titles: ['Startup Pitch Night', 'VC Office Hours', 'Founders & Funders Mixer', 'Tech Leaders Breakfast', 'Career Fair: Freshers', 'Product Demo Day', 'Creators Economy Summit', 'SaaS Growth Meetup'],
    venues: ['Co-work Central', 'Startup Foundry', 'The Boardroom Café', 'Innovation Hub', 'Convention Hall'],
    desc: 'Meet founders, operators and investors. Short talks, open networking and live pitches.',
    tiers: [['Attendee', 0, 150], ['Founder Pass (pitch slot)', 999, 15]], labels: ['NETWORKING', 'STARTUPS', 'PITCH NIGHT'] },
  gaming: { w: 0.8, wk: 2.2, hours: [14, 15, 18], dur: 4, tags: ['gaming', 'esports', 'students'],
    titles: ['Valorant Community Cup', 'BGMI Squad Showdown', 'FIFA Weekend League', 'Retro Arcade Night', 'Chess Blitz Open', 'LAN Party Classic', 'Tekken Tournament'],
    venues: ['Respawn Gaming Café', 'Level Up Arena', 'The LAN Room', 'Pixel Lounge'],
    desc: 'Compete, spectate or just play casually. Prize pool for winners, snacks for everyone.',
    tiers: [['Spectator', 99, 100], ['Player Entry', 349, 64]], labels: ['ESPORTS', 'GAMING', 'TOURNAMENT'] },
  wellness: { w: 0.8, wk: 2.2, hours: [6, 7, 8, 17], dur: 1.5, tags: ['wellness', 'spiritual', 'chill'],
    titles: ['Sound Bath Meditation', 'Sunrise Yoga Flow', 'Breathwork Circle', 'Mindful Morning Walk', 'Reiki & Relax', 'Laughter Yoga Club', 'Journaling Circle'],
    venues: ['Stillness Studio', 'Lotus Garden', 'Prana Space', 'The Calm Room'],
    desc: 'Slow down with a guided session. Mats provided. Arrive 10 minutes early.',
    tiers: [['Session', 399, 30]], labels: ['WELLNESS', 'MEDITATION', 'YOGA'] },
  screenings: { w: 0.7, wk: 1.8, hours: [18, 19, 20], dur: 3, tags: ['film', 'chill', 'date'],
    titles: ['Rooftop Movie Night', 'Cult Classics Screening', 'Indie Short Film Fest', 'Match Screening: Big Game Night', 'Anime Movie Marathon', 'Documentary + Q&A'],
    venues: ['Rooftop Cinema', 'The Screening Room', 'Film Club Hall', 'Projector Café'],
    desc: 'Big screen, bean bags and popcorn. Discussion after the film for those who stay.',
    tiers: [['Bean Bag', 349, 60], ['Couple Sofa', 799, 12]], labels: ['SCREENING', 'FILM CLUB', 'MOVIE NIGHT'] },
};

// City-specific boosts so each city feels different
const CITY_BIAS = {
  goa: { parties: 2, music: 1.4, wellness: 1.5, food: 1.3, hackathons: 0.4, networking: 0.4 },
  bengaluru: { hackathons: 2, meetups: 1.6, networking: 1.8, gaming: 1.3 },
  hyderabad: { hackathons: 1.6, networking: 1.4, food: 1.3 },
  pune: { hackathons: 1.3, meetups: 1.3, gaming: 1.3 },
  mumbai: { comedy: 1.6, theatre: 1.4, parties: 1.3, screenings: 1.2 },
  delhi: { comedy: 1.3, bhajan: 1.4, food: 1.3, arts: 1.2, festivals: 1.2 },
  kolkata: { theatre: 1.6, arts: 1.5, festivals: 1.6, openmic: 1.3 },
  jaipur: { arts: 1.6, festivals: 1.4, food: 1.2 },
  lucknow: { openmic: 1.6, food: 1.5, arts: 1.2 },
  chennai: { music: 1.3, arts: 1.3, sports: 1.2 },
  kochi: { arts: 1.4, food: 1.3, music: 1.2 },
  indore: { food: 1.8, bhajan: 1.5 },
  ahmedabad: { festivals: 1.8, bhajan: 1.4, food: 1.3 },
  chandigarh: { sports: 1.4, parties: 1.2, comedy: 1.2 },
};

module.exports = { CITIES, CATEGORIES, TEMPLATES, CITY_BIAS };
